project:
  type: website
  output-dir: docs

website:
  title: "Timothy Pistotti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: about.qmd
        text: About
  
format:
  html:
    theme: darkly
    css: styles.css
    toc: true