project:
  type: website
  output-dir: docs

website:
  title: "Timothy Pistotti"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: about.qmd
        text: About
      - href: contact.qmd   # <-- Add this new link
        text: Contact
  
format:
  html:
    theme: 
      light: cyborg
      dark: cerulean
    css: styles.css
    toc: true